### PR TITLE
put a sentence add featureA

### PR DESCRIPTION
**Pull request by Eunjung17**
Completed featureA

### CODE REVIEW

**Comment by EmSmith-Navy** [comment]
are you still having merge issues?

**Comment by Eunjung17** [comment]
Hi, I didn't do it yet. I guess one of us can do about Merge Conflicts  except feature-A. Do you wanna do that? Otherwise, I can do tonight or tomorrow morning.

**Comment by Anthonybasco** [comment]
I merged both of yours but it got rid of my "to improve is to change", but i can fix that in editor, should there be two instances of "There is nothing permanent, except change"? and should i just add my thing with edit in Github?

**Comment by Eunjung17** [comment]
In your terninal, first put 'git checkout main', second put 'git pull origin main'. Then you can see all merged result.

**Pull request merged**
